/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Circle_AccountTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Circle_AccountTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        //dlrs.RollupService.testHandler(new Circle_Account__c());
    }
}