/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_slackv2_Slack_AuthTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_slackv2_Slack_AuthTrigger to be invoked, fails the test if org config or other Apex code prevents this.
       //dlrs.RollupService.testHandler(new slackv2__Slack_Auth__c());
    }
}